meta_form/urls.py
from django.urls import path

from meta_form import views

app_name = 'meta_form'
urlpatterns = [
    path('', views.index, name='index'),
    path('download/<int:metadata_id>/', views.download_all_metadata, name='download_metadata')
]

pluggy_server/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('form/', include('meta_form.urls')),
] + debug_toolbar_urls()

meta_form/models.py
from django.db import models


class DataFormat(models.Model):
    name = models.CharField(max_length=10, unique=True, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Data Format'
        verbose_name_plural = 'Data Format'


class DegreeOfAggregation(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True, null=False)
    description = models.TextField(blank=True, null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Degree of Aggregation'
        verbose_name_plural = 'Degrees of Aggregation'


class ResearchMetadata(models.Model):
    data_provider = models.CharField(max_length=100, blank=False, null=False)
    data_format = models.ForeignKey(DataFormat, on_delete=models.PROTECT, related_name='research_metadata',
                                    null=False, blank=False)
    degree_of_aggregation = models.ForeignKey(DegreeOfAggregation, on_delete=models.PROTECT,
                                              related_name='research_metadata',
                                              null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.data_provider

    class Meta:
        verbose_name = 'Research Metadata'
        verbose_name_plural = 'Research Metadata'
        ordering = ['-created_at']

meta_form/forms.py
from django import forms

from meta_form.models import ResearchMetadata


class ResearchMetadataForm(forms.ModelForm):
    class Meta:
        model = ResearchMetadata
        fields = '__all__'

meta_form/views.py
import zipfile

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from meta_form.forms import ResearchMetadataForm
from meta_form.models import ResearchMetadata
from meta_form.pluggy_specs import plugin_manager


def index(req):
    form = ResearchMetadataForm()

    if req.method == 'POST':
        form = ResearchMetadataForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect('meta_form:index')

    research = ResearchMetadata.objects.all().select_related('data_format', 'degree_of_aggregation')
    return HttpResponse(render(req, 'index.html', context={
        'form': form,
        'research': research
    }))


def download_all_metadata(request, metadata_id: int):
    research_meta_data = get_object_or_404(ResearchMetadata.objects.select_related('data_format', 'degree_of_aggregation'),
                                           pk=metadata_id)
    response = HttpResponse(content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename="metadata_files.zip"'
    with zipfile.ZipFile(response, 'w') as zf:
        res = plugin_manager.hook.meta_data_download_format(meta_data=research_meta_data)
        for (content, format_with_name) in res:
            zf.writestr(format_with_name, content)

    return response

meta_form/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Metadata form
{% endblock %}
{% block extra_head %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block content %}
    <div class="newsletter-subscribe">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Research metadata form</h2>
            </div>
            <form class="form-inline" method="post">
                {% csrf_token %}
                {% for f in form %}
                    <div class="form-group mb-3"><label for="{{ f.id_for_label }}"
                                                        class="mx-3">{{ f.label }}:</label>{{ f }}</div>
                {% endfor %}
                <div class="row-form-errors">{{ form.errors }}</div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="container mt-3">
            <ol class="list-group list-group-numbered">
                {% for r in research %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">{{ r.data_provider }}</div>
                            <span>Created at: {{ r.created_at }}</span>
                            <br/>
                            <span>Data format: {{ r.data_format }}</span>
                            <br/>
                            <span>Degree of aggregation: {{ r.degree_of_aggregation }}</span>
                        </div>
                        <a class="badge text-bg-primary rounded-pill"
                                href="{% url 'meta_form:download_metadata' metadata_id=r.pk %}">Download METADATA</a>
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block extra_script %}
{% endblock %}
</body>
</html>